[project]
name = 'Tutorial-Hell-Escape-Velocity-Calculator'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.side-project-graveyard-memorial]
path = 'contracts/side-project-graveyard-memorial.clar'
clarity_version = 3
epoch = 'latest'

[contracts.tutorial-completion-abandonment-tracker]
path = 'contracts/tutorial-completion-abandonment-tracker.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
