[project]
name = 'Tutorial-Hell-Escape-Velocity-Calculator'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.course-completion-to-real-project-ratio]
path = 'contracts/course-completion-to-real-project-ratio.clar'
clarity_version = 3
epoch = '3.2'

[contracts.fresh-start-syndrome-frequency]
path = 'contracts/fresh-start-syndrome-frequency.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
